Repository chrisdev-ts/ratacueva-web, pull requests merged in 2025-08, with the labels that each got.

#19 feat: add authentication services and integrate login/register functi…
  package-lock.json
  package.json
  src/app/(auth)/login/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(dashboard)/employees/[employeeID]/page.tsx
  src/app/(dashboard)/employees/add/page.tsx
  src/app/(dashboard)/employees/page.tsx
  src/app/(dashboard)/employers/page.tsx
  src/app/(dashboard)/items/[itemID]/edit/page.tsx
  src/app/(dashboard)/items/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/sales/[saleID]/page.tsx
  src/app/(dashboard)/sales/page.tsx
  src/app/(dashboard)/shipments/page.tsx
  src/app/layout.tsx
  src/components/ReactQueryProvider.tsx
  src/components/atoms/Input.tsx
  src/components/features/dashboard/atoms/StatusTag.tsx
  src/components/features/dashboard/organisms/Sidebar.tsx
  src/components/guard/AuthGuard.tsx
  src/components/organisms/Header.tsx
  src/hook/dashboard/useEmployees.ts
  src/hook/dashboard/useProduct.ts
  src/hook/dashboard/useSales.ts
  src/lib/react-query-client.ts
  src/lib/salesData.ts
  src/services/auth/login.ts
  src/services/auth/register.ts
Labels: enhancement

#22 Refactor/interfaces.md
  INTERFACES.md
Labels: documentation

#18 refactor: reorganize home and search components, improve UI atoms, an…
  package-lock.json
  src/components/features/home/organisms/Header.tsx
Labels: help wanted, invalid

#24 refactor: removing the API folder from src/app
  src/app/api/auth/route.ts
  src/app/api/orders/route.ts
  src/app/api/products/route.ts
Labels: duplicate

#26 refactor: move AuthGuard to src/ and add query provider
  src/app/(dashboard)/employees/page.tsx
  src/app/(dashboard)/items/page.tsx
  src/app/(dashboard)/layout.tsx
  src/app/(dashboard)/sales/[saleID]/page.tsx
  src/app/(dashboard)/sales/page.tsx
  src/app/layout.tsx
  src/components/atoms/badge.tsx
  src/components/atoms/card.tsx
  src/components/atoms/label.tsx
  src/components/atoms/radio-group.tsx
  src/components/features/home/molecules/DualReviewsCarousel.tsx
  src/components/features/home/molecules/InfiniteReviewsCarousel.tsx
  src/components/features/home/molecules/ReviewsCarousel.tsx
  src/components/features/home/organisms/CommunitySection.tsx
  src/guards/AuthGuard.tsx
  src/hook/dashboard/useEmployees.ts
  src/hook/dashboard/useProduct.ts
  src/hook/dashboard/useSales.ts
  src/libs/accessoryProducts.ts
  src/libs/componentProducts.ts
  src/libs/computerProducts.ts
  src/libs/featuredProducts.ts
  src/libs/gamingProducts.ts
  src/libs/index.ts
  src/libs/salesData.ts
  src/libs/userReviews.ts
  src/libs/utils.ts
  src/querys/ReactQueryClient.ts
  src/querys/ReactQueryProvider.tsx
Labels: enhancement

#29 refactor: adjust padding and margin in overview dashboard interface
  src/app/(dashboard)/employees/page.tsx
  src/app/(dashboard)/items/page.tsx
  src/app/(dashboard)/overview/page.tsx
  src/app/(dashboard)/sales/page.tsx
  src/app/(dashboard)/shipments/page.tsx
  src/components/atoms/Typography/BaseTypography.tsx
  src/components/features/dashboard/organisms/Sidebar.tsx
  src/components/features/dashboard/templates/DashboardContentLayout.tsx
Labels: enhancement

#30 refactor: update BaseTypography component to use Tailwind CSS classes…
  src/app/globals.css
  src/components/atoms/Typography/BaseTypography.tsx
Labels: enhancement

#31 feat: replace default favicon with custom site icon
  src/app/layout.tsx
Labels: enhancement

#35 refactor: improved appearance of header, footer, and buttons
  src/components/atoms/Button.tsx
  src/components/features/home/organisms/Footer.tsx
  src/components/features/home/organisms/Header.tsx
  src/components/organisms/Navbar.tsx
Labels: enhancement

#40 fix(new-card): finish add card interface with service logic
  src/app/(shop)/cart/new-card/page.tsx
  src/app/(shop)/settings/addresses/new-address/page.tsx
Labels: enhancement

#42 feat(payment): integrate payment methods fetching and add purchase su…
  src/app/(shop)/cart/new-card/page.tsx
  src/app/(shop)/cart/payment-card-options/page.tsx
  src/components/organisms/PurchaseSummary.tsx
  src/services/payment/paymentOptions.ts
Labels: enhancement

#41 reactor: update readme to include more information
  README.md
  public/images/screenshots/cart.png
  public/images/screenshots/dashboard.png
  public/images/screenshots/home.png
  public/images/screenshots/products.png
Labels: documentation

#46 fix: typescript eslint optimization
  package-lock.json
  package.json
  src/app/(auth)/forgot-password/page.tsx
  src/app/(auth)/login/page.tsx
  src/app/(auth)/password-reset-success/page.tsx
  src/app/(auth)/register/page.tsx
  src/app/(auth)/reset-password/[auth]/page.tsx
  src/app/(dashboard)/employees/[employeeID]/page.tsx
  src/app/(dashboard)/employees/add/page.tsx
  src/app/(dashboard)/employees/page.tsx
  src/app/(dashboard)/items/[itemID]/edit/page.tsx
  src/app/(dashboard)/items/page.tsx
  src/app/(dashboard)/sales/[saleID]/page.tsx
  src/app/(dashboard)/sales/page.tsx
  src/app/(dashboard)/shipments/page.tsx
  src/app/(shop)/cart/delivery-day/page.tsx
  src/app/(shop)/cart/form-page/page.tsx
  src/app/(shop)/cart/new-card/page.tsx
  src/app/(shop)/cart/payment-card-options/page.tsx
  src/app/(shop)/cart/payment-points/page.tsx
  src/app/(shop)/cart/success/page.tsx
  src/app/(shop)/search/page.tsx
  src/app/(shop)/settings/addresses/[id]/edit/page.tsx
  src/app/(shop)/settings/addresses/new-address/page.tsx
  src/app/(shop)/settings/addresses/page.tsx
  src/app/(shop)/settings/purchases/page.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/Input.tsx
  src/components/atoms/Textarea.tsx
  src/components/atoms/Typography/types.ts
  src/components/features/dashboard/atoms/BaseTable.tsx
  src/components/features/home/atoms/ErrorBoundary.tsx
  src/components/features/home/atoms/SearchSuggestions.tsx
  src/components/features/home/molecules/SocialMediaButtons.tsx
  src/components/features/privacy-policy/molecules/InfoCardHeader.tsx
  src/components/features/privacy-policy/organisms/PrivacyPolicyCard.tsx
  src/components/templates/ContentLayout.tsx
  src/guards/AuthGuard.tsx
  src/hook/dashboard/useEmployees.ts
  src/hook/dashboard/useShipments.ts
  src/hook/useOrders.ts
  src/hook/useProducts.ts
  src/services/home/products/index.tsx
  src/services/settings/address/addresses.ts
  src/services/settings/address/index.ts
Labels: refactor
